server:
  port: 8002
mysql:
  host: 127.0.0.1
  port: 33306
  user: root
  password: root1234
  database: shopdevgo
  maxIdleConns: 10 # Maximum number of idle connections
  maxOpenConns: 100 # Maximum number of open connections
  connMaxLifetime: 3600 # Maximum connection lifetime in seconds